export const ERROR_CODES = {
  MISSING_REQUEST_BODY: "MISSING_REQUEST_BODY",
  API_HANDLER_ERROR: "API_HANDLER_ERROR",
  AUTH_SESSION_FAILED: "AUTH_SESSION_FAILED",
  MATCH_PARTICIPATION_FAILED: "MATCH_PARTICIPATION_FAILED",
  PROTECTED_ROUTE_FAILED: "PROTECTED_ROUTE_FAILED",
  MISSING_SERVER_CONTEXT: "MISSING_SERVER_CONTEXT",
  MISSING_MATCH_CONTEXT: "MISSING_MATCH_CONTEXT",
  MISSING_RESULT_CONTEXT: "MISSING_RESULT_CONTEXT",
  MISSING_REPOSITORIES: "MISSING_REPOSITORIES",
  PERSIST_MATCH_RESULT_FAILED: "PERSIST_MATCH_RESULT_FAILED",
  PERSIST_REWARD_CLAIM_FAILED: "PERSIST_REWARD_CLAIM_FAILED",
  MISSING_IDEMPOTENCY_STORE: "MISSING_IDEMPOTENCY_STORE",
  IDEMPOTENCY_CHECK_FAILED: "IDEMPOTENCY_CHECK_FAILED",
  IDEMPOTENCY_SAVE_FAILED: "IDEMPOTENCY_SAVE_FAILED",
  MISSING_SESSION_STORE: "MISSING_SESSION_STORE",
  SESSION_STORE_VALIDATION_FAILED: "SESSION_STORE_VALIDATION_FAILED",
  STORE_PROTECTED_ROUTE_FAILED: "STORE_PROTECTED_ROUTE_FAILED",
  MISSING_MATCH_STORE: "MISSING_MATCH_STORE",
  MATCH_STORE_VALIDATION_FAILED: "MATCH_STORE_VALIDATION_FAILED",
  STORE_MATCH_PROTECTED_ROUTE_FAILED: "STORE_MATCH_PROTECTED_ROUTE_FAILED"
};

export function createApiError(code, message, path = "", details = []) {
  return { code, message, path, details };
}
